# Prettier (formatter) configuration
---
singleQuote: true
semi: false
trailingComma: all
arrowParens: always
importOrder:
  - "<THIRD_PARTY_MODULES>"
  - "^@[/]"
  - "^[./]"
importOrderSeparation: true
importOrderParserPlugins:
  - "typescript"
  - "classProperties"
  - "decorators-legacy"

