name: Weekly Report
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 */2 * * *"}]
  # Lines below let you run workflow manually and on each commit
  push: {branches: ["master", "main"]}
  workflow_dispatch:
jobs:
  weekly-report:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup node.js with .nvmrc
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'

      - name: Install dependencies
        run: |
          corepack enable
          yarn set version berry
          yarn install --immutable 

      - name: Build project
        run: yarn build

      - name: Run script
        run: yarn start
        env:
          LARK_APP_ID: ${{ secrets.LARK_APP_ID }}
          LARK_APP_SECRET: ${{ secrets.LARK_APP_SECRET }}
          LARK_OPEN_ID: ${{ secrets.LARK_OPEN_ID }}
          COOKIE: ${{ secrets.COOKIE }}
